# Generated by Django 4.1.5 on 2023-02-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='seccion',
            field=models.CharField(max_length=50),
        ),
    ]
